### Getting booking details
GET http://localhost:8080/customerSupportAgent?sessionId=1&userMessage=Hi, when does my booking begin?

### Getting booking details - providing missing customer info (1)
GET http://localhost:8080/customerSupportAgent?sessionId=1&userMessage=My booking number is MS-777.

### Getting booking details - providing missing customer info (2)
GET http://localhost:8080/customerSupportAgent?sessionId=1&userMessage=My name is John Doe.


### Cancelling booking
GET http://localhost:8080/customerSupportAgent?sessionId=1&userMessage=Please cancel my booking.

### Cancelling booking - confirmation
GET http://localhost:8080/customerSupportAgent?sessionId=1&userMessage=Yes, cancel it.