import dev.langchain4j.data.embedding.Embedding;
import dev.langchain4j.model.embedding.EmbeddingModel;
import dev.langchain4j.model.embedding.Similarity;
import dev.langchain4j.model.huggingface.HuggingFaceEmbeddingModel;
import dev.langchain4j.model.inprocess.InProcessEmbeddingModel;

import java.io.IOException;

import static dev.langchain4j.model.inprocess.InProcessEmbeddingModelType.ALL_MINILM_L6_V2;

public class InProcessEmbeddingModelExamples {

    public static void main(String[] args) throws IOException {

        String text = "This is a test";

        // requires langchain4j-embeddings-all-minilm-l6-v2 Maven dependency
        EmbeddingModel inProcessModel = new InProcessEmbeddingModel(ALL_MINILM_L6_V2);
        Embedding inProcessEmbedding = inProcessModel.embed(text);
        System.out.println(inProcessEmbedding);

        // Now let's compare with the embedding generated by HuggingFace
        EmbeddingModel huggingFaceModel = HuggingFaceEmbeddingModel.builder()
                .modelId("sentence-transformers/all-MiniLM-L6-v2")
                .accessToken(System.getenv("HF_API_KEY"))
                .build();
        Embedding huggingFaceEmbedding = huggingFaceModel.embed(text);
        System.out.println(huggingFaceEmbedding);

        System.out.println(Similarity.cosine(
                inProcessEmbedding.vector(),
                huggingFaceEmbedding.vector()
        ));
        // 0.9999999964191233
    }
}
